### PR TITLE
Rewrite Method2

### PR DESCRIPTION
**Pull request by mattias-p**
These are quite extensive changes. I started writing review comments, but ended up feeling it would be easier to just write up an entire suggestion. Please review and let me know what you think.

There are some formal changes, like changing the contexts in which the method is applicable.
There are some structural changes to control flow. The intention is only to simplify.
There are some substantial clarifications with regard to the result set.
There are hopefully no undesired substantial changes to what result is produced for a given input. I've tried hard not to stay clear of those, but I may have misunderstood something.

Here's a rundown of the edits:
* Add preconditions that child zone exists and is delegated
* Clarify case handling of case sensitivity
* Simplify the high-level structure of control flow
* Simplify dealing with repetitions in the result set
* Refer to every intermediate value by name
* Remove numbered references to other steps

### CODE REVIEW

**Comment by matsduf** [comment]
@mattias-p, this would be a dramatically change of format compared to the the work I have done so far. I cannot see that **bold** is better than *italic*. I assume that your idea is that all method and test case specifications are rewritten. I do not see the value.

I think it would be more fruitful to focus on error, problems or unclear parts of the current text. The reviews from @JohanIIS have been very helpful.

**Comment by mattias-p** [comment]
I'm saying that this is a great improvement in clarity over the previous version, and that there's great value in this clarity.
 * The control flow easier to follow.
 * It is easier to see what value is being operated on and where it came from.
 * It is easier to see how each input is used.
 * It is easier to see how the return value is constructed.
 * It avoids unnecessary complexities of accepting extra inputs for the only purpose of passing them through or introducing new error conditions.

**Comment by matsduf** [comment]
@mattias-p, right now I do not see the value of re-doing the re-writing all the specifications in a new format. On the last F2F meeting it was agreed that I should re-write the specifications in the format that I have used.

I think it would be more fruitful to focus on error, problems or unclear parts of the current text.

**Comment by mattias-p** [comment]
This is not a rewrite of all specifications. It is a rewrite of a particularly unclear specification. I started writing review comments for the previous version but I gave up.

This work builds upon the fine work you've done in clearing up what queries need to be sent. Without your work I couldn't have done this. However this description is much clearer than the previous version. It would take several iterations and lots of time, both yours and mine, to get the previous version into this good a shape.

I don't see the problem of accepting this as a clarification. Do you think it is not a clearer description?

**Pull request closed without merging**
